eccomi
/workspaces/nespolo/settings.py changed, reloading.
2024-01-26 17:15:44,251 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-26 17:15:52,964 (INFO - commanda.views - eccomi)
2024-01-26 17:26:35,643 (INFO - django.utils.autoreload - /workspaces/manage.py changed, reloading.)
2024-01-26 17:27:32,700 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-26 17:27:38,935 (INFO - commanda.views - eccomi)
2024-01-26 17:27:56,105 (INFO - django.utils.autoreload - /workspaces/nespolo/wsgi.py changed, reloading.)
2024-01-26 17:27:57,293 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-26 17:28:34,980 (INFO - django.utils.autoreload - /workspaces/nespolo/wsgi.py changed, reloading.)
2024-01-26 17:28:36,152 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-26 17:29:04,839 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-26 17:29:06,078 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-26 17:34:03,002 (WARNING - django.request - Not Found: /favicon.ico)
2024-01-26 17:45:24,742 (WARNING - django.request - Not Found: /commanda/product/25)
2024-01-28 07:32:01,763 (WARNING - django.request - Not Found: /favicon.ico)
2024-01-28 08:34:51,725 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 08:48:54,139 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 08:49:22,836 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 08:52:07,423 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 08:52:08,507 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 08:52:40,317 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 08:52:41,584 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 08:59:14,109 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 08:59:15,292 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:00:17,094 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 09:00:18,364 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:04:03,000 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:05:22,233 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 09:05:23,443 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:06:26,427 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 09:06:27,559 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:08:55,235 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:14:40,453 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 09:14:41,648 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:15:08,650 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 09:15:09,825 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:15:52,621 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:23:57,251 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 09:23:58,509 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:26:59,872 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 09:27:01,277 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 09:27:19,644 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 09:27:20,972 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 15:27:25,905 (WARNING - django.request - Not Found: /favicon.ico)
2024-01-28 15:32:54,392 (INFO - django.utils.autoreload - /workspaces/nespolo/celery.py changed, reloading.)
2024-01-28 15:32:55,933 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 15:35:05,678 (INFO - commanda.views - eccomi)
2024-01-28 15:36:11,828 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-01-28 15:36:13,461 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 15:36:21,029 (INFO - commanda.views - eccomi)
2024-01-28 15:37:13,911 (INFO - commanda.views - eccomi)
2024-01-28 15:38:09,484 (INFO - commanda.views - eccomi)
2024-01-28 15:42:54,286 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 15:42:55,662 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 15:43:23,997 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 15:43:25,371 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 15:43:53,404 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 15:43:54,803 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 15:44:06,239 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 15:46:01,488 (INFO - flower.command - Visit me at http://0.0.0.0:5555)
2024-01-28 15:46:01,493 (INFO - flower.command - Broker: redis://redis:6379/1)
2024-01-28 15:46:01,498 (INFO - flower.command - Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'commanda.tasks.notify_customer'])
2024-01-28 15:46:01,514 (INFO - kombu.mixins - Connected to redis://redis:6379/1)
2024-01-28 15:46:02,571 (WARNING - flower.inspector - Inspect method active_queues failed)
2024-01-28 15:46:02,581 (WARNING - flower.inspector - Inspect method reserved failed)
2024-01-28 15:46:02,581 (WARNING - flower.inspector - Inspect method revoked failed)
2024-01-28 15:46:02,588 (WARNING - flower.inspector - Inspect method stats failed)
2024-01-28 15:46:02,589 (WARNING - flower.inspector - Inspect method registered failed)
2024-01-28 15:46:02,595 (WARNING - flower.inspector - Inspect method scheduled failed)
2024-01-28 15:46:02,596 (WARNING - flower.inspector - Inspect method active failed)
2024-01-28 15:46:02,597 (WARNING - flower.inspector - Inspect method conf failed)
2024-01-28 15:47:23,461 (INFO - django.utils.autoreload - /workspaces/nespolo/settings/common.py changed, reloading.)
2024-01-28 15:47:24,817 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-01-28 15:47:34,889 (INFO - flower.command - Visit me at http://0.0.0.0:5555)
2024-01-28 15:47:34,894 (INFO - flower.command - Broker: redis://redis:6379/1)
2024-01-28 15:47:34,898 (INFO - flower.command - Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'commanda.tasks.notify_customer'])
2024-01-28 15:47:34,913 (INFO - kombu.mixins - Connected to redis://redis:6379/1)
2024-01-28 15:47:35,956 (WARNING - flower.inspector - Inspect method reserved failed)
2024-01-28 15:47:35,958 (WARNING - flower.inspector - Inspect method stats failed)
2024-01-28 15:47:35,966 (WARNING - flower.inspector - Inspect method active_queues failed)
2024-01-28 15:47:35,967 (WARNING - flower.inspector - Inspect method scheduled failed)
2024-01-28 15:47:35,967 (WARNING - flower.inspector - Inspect method active failed)
2024-01-28 15:47:35,968 (WARNING - flower.inspector - Inspect method conf failed)
2024-01-28 15:47:35,969 (WARNING - flower.inspector - Inspect method revoked failed)
2024-01-28 15:47:35,972 (WARNING - flower.inspector - Inspect method registered failed)
2024-01-28 15:48:09,859 (INFO - flower.command - Visit me at http://0.0.0.0:5555)
2024-01-28 15:48:09,864 (INFO - flower.command - Broker: redis://redis:6379/1)
2024-01-28 15:48:09,869 (INFO - flower.command - Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'commanda.tasks.notify_customer'])
2024-01-28 15:48:09,886 (INFO - kombu.mixins - Connected to redis://redis:6379/1)
2024-01-28 15:48:10,942 (WARNING - flower.inspector - Inspect method scheduled failed)
2024-01-28 15:48:10,944 (WARNING - flower.inspector - Inspect method stats failed)
2024-01-28 15:48:10,953 (WARNING - flower.inspector - Inspect method active_queues failed)
2024-01-28 15:48:10,955 (WARNING - flower.inspector - Inspect method revoked failed)
2024-01-28 15:48:10,958 (WARNING - flower.inspector - Inspect method active failed)
2024-01-28 15:48:10,959 (WARNING - flower.inspector - Inspect method registered failed)
2024-01-28 15:48:10,960 (WARNING - flower.inspector - Inspect method reserved failed)
2024-01-28 15:48:10,960 (WARNING - flower.inspector - Inspect method conf failed)
2024-01-28 15:50:14,412 (INFO - commanda.views - eccomi)
2024-01-28 15:50:27,108 (INFO - flower.command - Visit me at http://0.0.0.0:5555)
2024-01-28 15:50:27,112 (INFO - flower.command - Broker: redis://redis:6379/1)
2024-01-28 15:50:27,115 (INFO - flower.command - Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'commanda.tasks.notify_customer'])
2024-01-28 15:50:27,131 (INFO - kombu.mixins - Connected to redis://redis:6379/1)
2024-01-28 15:50:37,981 (INFO - commanda.views - eccomi)
2024-01-28 15:51:43,662 (INFO - commanda.views - eccomi)
2024-01-28 17:25:08,864 (INFO - commanda.views - eccomi)
2024-01-28 18:49:57,212 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 00:59:51,664 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 01:02:51,750 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 01:03:02,638 (WARNING - django.request - Not Found: /favicon.ico)
2024-02-04 01:03:10,134 (ERROR - django.request - Internal Server Error: /commanda/commande/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'my_db.commanda_commanda' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'my_db.commanda_commanda' doesn't exist")
2024-02-04 01:03:18,990 (ERROR - django.request - Internal Server Error: /commanda/products/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'my_db.commanda_product' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'my_db.commanda_product' doesn't exist")
2024-02-04 01:05:13,217 (WARNING - django.request - Not Found: /favicon.ico)
2024-02-04 08:41:37,162 (WARNING - django.request - Not Found: /commanda/commande/tavoli/)
2024-02-04 08:41:55,936 (WARNING - django.request - Not Found: /commanda/commande/tavoli/)
2024-02-04 08:41:58,577 (WARNING - django.request - Not Found: /commanda/commande/tavoli/)
2024-02-04 08:46:24,715 (INFO - django.utils.autoreload - /workspaces/commanda/urls.py changed, reloading.)
2024-02-04 08:46:26,250 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 08:47:22,020 (INFO - django.utils.autoreload - /workspaces/commanda/urls.py changed, reloading.)
2024-02-04 08:47:23,249 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 08:47:33,243 (INFO - django.utils.autoreload - /workspaces/commanda/urls.py changed, reloading.)
2024-02-04 08:47:34,522 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 08:47:50,329 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-02-04 08:47:51,441 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 08:48:14,178 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-02-04 08:48:15,284 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 08:48:27,510 (INFO - django.utils.autoreload - /workspaces/commanda/urls.py changed, reloading.)
2024-02-04 08:48:29,080 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 08:48:30,642 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-02-04 08:48:32,025 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 09:02:35,403 (INFO - django.utils.autoreload - /workspaces/commanda/urls.py changed, reloading.)
2024-02-04 09:02:37,003 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 09:03:00,650 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-02-04 09:03:01,961 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 12:36:03,335 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-02-04 12:36:04,784 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 12:55:01,403 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-02-04 12:55:02,912 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 12:55:48,537 (INFO - django.utils.autoreload - /workspaces/commanda/urls.py changed, reloading.)
2024-02-04 12:55:49,864 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 13:00:00,808 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-02-04 13:00:02,483 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 13:03:46,863 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-02-04 13:03:48,199 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
2024-02-04 13:05:32,929 (INFO - django.utils.autoreload - /workspaces/commanda/views.py changed, reloading.)
2024-02-04 13:05:34,200 (INFO - django.utils.autoreload - Watching for file changes with StatReloader)
